### PR TITLE
[FIX]: Removed unnecessary padding in logo when in mobile view

### LINKED ISSUE #179: [BUG] Navbar icons position changes in mobile view
### Problem subject

- [x] Other - UI

### Description

Toggle Button and Hamburger Button goes to next line in mobile view

Screenshot:
image

### Expected behavior/contents

Icons should be placed at right side

### Actual behavior/contents

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Simperfy**
#### Description of the change
- Removed unnecessary horizontal padding in logo when in mobile view
- Note that the UI will still wrap if the screen width gets very small *(<352)*. I believe that most mobile device is greater than this width so there should be nothing to worry about. *If we need to support even smaller device we might need to shrink the logo.*
- fixes #179

#### Screenshots

Current design:
image

Proposed changes:
image

#### Checklist

**I agree to the following :-**

* [x]   Added description of the change
* [x]   I've read the [contributing guidelines](https://github.com/web3community/devprotocol.xyz/blob/main/CONTRIBUTING.md)
* [x]   Search previous suggestions before making a new PR, as yours may be a duplicate.
* [x]   I acknowledge that all my contributions will be made under the project's license.

Notes (**optional**): 

<a href="https://gitpod.io/#https://github.com/web3community/devprotocol.xyz/pull/184"></a>

### CODE REVIEW

File: src/components/Global/Navbar.vue [hunk 1]
```diff
@@ -22,7 +22,7 @@
       "
     >
       <!-- Dev Protocol Icon -->
-      <a href="https://devprotocol.xyz" class="text-gray-900 p-4">
+      <a href="https://devprotocol.xyz" class="text-gray-900 md:p-4 py-4">
```
Comment (Simperfy) [inline src/components/Global/Navbar.vue:25]: Note: This is the only real change I made don't mind the ones below, they're caused by a plugin in my editor.

**Review by krishguptadev — APPROVED** [review]

**Review by shuklaritvik06 — APPROVED** [review]
LGTM
